let homepage = document.querySelector('.section-g')
let memberpage = document.querySelector('.section-three')
let scrimspage = document.querySelector('.section-f')
let timelinespage = document.querySelector('.section-two')
memberpage.style.display = "none"
scrimspage.style.display = "none"
timelinespage.style.display = "none"
member.addEventListener("click", ()=>{
    member.style.borderBottom = "4px solid rgb(11, 179, 240)"
    member.style.color = "rgb(115, 214, 250)"
    timelines.style.borderBottom = "4px solid transparent"
    timelines.style.color = "white"
    scrims.style.borderBottom = "4px solid transparent"
    scrims.style.color = "white"
    home.style.borderBottom = "4px solid transparent"
    home.style.color = "white"
    memberpage.style.display = "block"
    scrimspage.style.display = "none"
    homepage.style.display = "none"
    timelinespage.style.display = "none"
})
home.addEventListener("click", ()=>{
    home.style.borderBottom = "4px solid rgb(11, 179, 240)"
    home.style.color = "rgb(115, 214, 250)"
    member.style.borderBottom = "4px solid transparent"
    member.style.color = "white"
    timelines.style.borderBottom = "4px solid transparent"
    timelines.style.color = "white"
    scrims.style.borderBottom = "4px solid transparent"
    scrims.style.color = "white"
    homepage.style.display = "block"
    memberpage.style.display = "none"
    scrimspage.style.display = "none"
    timelinespage.style.display = "none"
})
scrims.addEventListener("click", ()=>{
    scrims.style.borderBottom = "4px solid rgb(11, 179, 240)"
    scrims.style.color = "rgb(115, 214, 250)"
    home.style.borderBottom = "4px solid transparent"
    home.style.color = "white"
    member.style.borderBottom = "4px solid transparent"
    member.style.color = "white"
    timelines.style.borderBottom = "4px solid transparent"
    timelines.style.color = "white"
    scrimspage.style.display = "block"
    homepage.style.display = "none"
    memberpage.style.display = "none"
    timelinespage.style.display = "none"
})
timelines.addEventListener("click", ()=>{
    timelines.style.borderBottom = "4px solid rgb(11, 179, 240)"
    timelines.style.color = "rgb(115, 214, 250)"
    scrims.style.borderBottom = "4px solid transparent"
    scrims.style.color = "white"
    home.style.borderBottom = "4px solid transparent"
    home.style.color = "white"
    member.style.borderBottom = "4px solid transparent"
    member.style.color = "white"
    timelinespage.style.display = "block"
    scrimspage.style.display = "none"
    homepage.style.display = "none"
    memberpage.style.display = "none"
})
let pagesa = document.querySelector('.pages-a')
let pagesb = document.querySelector('.pages-b')
let pagesc = document.querySelector('.pages-c')
pagesa.style.display = "block"
pagesb.style.display = "none"
pagesc.style.display = "none"
upcoming.addEventListener("click", ()=>{
    upcoming.style.color = "rgb(115, 214, 250)"
    ongoing.style.color = "white"
    results.style.color = "white"
    pagesa.style.display = "block"
    pagesb.style.display = "none"
    pagesc.style.display = "none"
})
ongoing.addEventListener("click", ()=>{
    ongoing.style.color = "rgb(115, 214, 250)"
    upcoming.style.color = "white"
    results.style.color = "white"
    pagesb.style.display = "block"
    pagesa.style.display = "none"
    pagesc.style.display = "none"
})
results.addEventListener("click", ()=>{
    results.style.color = "rgb(115, 214, 250)"
    ongoing.style.color = "white"
    upcoming.style.color = "white"
    pagesc.style.display = "block"
    pagesa.style.display = "none"
    pagesb.style.display = "none"
})